
##################################
##### Final CHL heatmap prep #####
##################################

#this scripts creates the actual final chl heatmaps

#packages
library(plyr)
library(gplots)
library(grDevices)

#open subsetted final chl data file
wq <-read.csv( "X:/ArcProject/Arc_Heatmaps/Arc_wqt_snapped_corrected/Arc_Final_CHL_All.csv")

##subset by slough
wqbk <- subset(wq,wq$RID=='BK')
wqcc <- subset(wq,wq$RID=='CC')
wqln <- subset(wq,wq$RID=='LN')
wqca <- subset(wq,wq$RID=='CA')
wqul <- subset(wq,wq$RID=='UL')
wqhs <- subset(wq,wq$RID=='HS')
wqhspc <- subset(wq,wq$RID=='HSPC')
wqmz <- subset(wq,wq$RID=='MZ')
wqnsdv <- subset(wq,wq$RID=='NSDV')
wqbr <- subset(wq,wq$RID=='BR')

#subset labels
wqbk2 <- subset(wqbk,select=(Labels))
wqcc2 <- subset(wqcc,select=(Labels))
wqln2 <- subset(wqln,select=(Labels))
wqca2 <- subset(wqca,select=(Labels))
wqul2 <- subset(wqul,select=(Labels))
wqhs2 <- subset(wqhs,select=(Labels))
wqhspc2 <- subset(wqhspc,select=(Labels))
wqmz2 <- subset(wqmz,select=(Labels))
wqnsdv2 <- subset(wqnsdv,select=(Labels))
wqbr2 <- subset(wqbr, select=c(Labels))

##Save as csv for each slough
write.csv(wqbk, "X:/ArcProject/Arc_Heatmaps/Arc_wqt_snapped_corrected/Arc_Final_CHL_BKwqtst.csv")
write.csv(wqcc, "X:/ArcProject/Arc_Heatmaps/Arc_wqt_snapped_corrected/Arc_Final_CHL_CCwqtst.csv")
write.csv(wqln, "X:/ArcProject/Arc_Heatmaps/Arc_wqt_snapped_corrected/Arc_Final_CHL_LNwqtst.csv")
write.csv(wqca, "X:/ArcProject/Arc_Heatmaps/Arc_wqt_snapped_corrected/Arc_Final_CHL_CAwqtst.csv")
write.csv(wqul, "X:/ArcProject/Arc_Heatmaps/Arc_wqt_snapped_corrected/Arc_Final_CHL_ULwqtst.csv")
write.csv(wqhs, "X:/ArcProject/Arc_Heatmaps/Arc_wqt_snapped_corrected/Arc_Final_CHL_HSwqtst.csv")
write.csv(wqhspc, "X:/ArcProject/Arc_Heatmaps/Arc_wqt_snapped_corrected/Arc_Final_CHL_HSPCwqtst.csv")
write.csv(wqmz, "X:/ArcProject/Arc_Heatmaps/Arc_wqt_snapped_corrected/Arc_Final_CHL_MZwqtst.csv")
write.csv(wqnsdv, "X:/ArcProject/Arc_Heatmaps/Arc_wqt_snapped_corrected/Arc_Final_CHL_NSDVwqtst.csv")
write.csv(wqbr, "X:/ArcProject/Arc_Heatmaps/Arc_wqt_snapped_corrected/Arc_Final_CHL_BRwqtst.csv")

##Re-open file
wqbk <- read.csv("X:/ArcProject/Arc_Heatmaps/Arc_wqt_snapped_corrected/Arc_Final_CHL_BKwqtst.csv")
wqcc <- read.csv("X:/ArcProject/Arc_Heatmaps/Arc_wqt_snapped_corrected/Arc_Final_CHL_CCwqtst.csv")
wqln <- read.csv("X:/ArcProject/Arc_Heatmaps/Arc_wqt_snapped_corrected/Arc_Final_CHL_LNwqtst.csv")
wqca <- read.csv( "X:/ArcProject/Arc_Heatmaps/Arc_wqt_snapped_corrected/Arc_Final_CHL_CAwqtst.csv")
wqul <- read.csv( "X:/ArcProject/Arc_Heatmaps/Arc_wqt_snapped_corrected/Arc_Final_CHL_ULwqtst.csv")
wqhs <- read.csv( "X:/ArcProject/Arc_Heatmaps/Arc_wqt_snapped_corrected/Arc_Final_CHL_HSwqtst.csv")
wqhspc <- read.csv( "X:/ArcProject/Arc_Heatmaps/Arc_wqt_snapped_corrected/Arc_Final_CHL_HSPCwqtst.csv")
wqmz <- read.csv( "X:/ArcProject/Arc_Heatmaps/Arc_wqt_snapped_corrected/Arc_Final_CHL_MZwqtst.csv")
wqnsdv <- read.csv( "X:/ArcProject/Arc_Heatmaps/Arc_wqt_snapped_corrected/Arc_Final_CHL_NSDVwqtst.csv")
wqbr <- read.csv( "X:/ArcProject/Arc_Heatmaps/Arc_wqt_snapped_corrected/Arc_Final_CHL_BRwqtst.csv")

##subset to get rid of "extra" columns
wqbk <- subset(wqbk,select=-c(RID, X, X.1, Labels))
wqcc <- subset(wqcc,select=-c(RID, X, X.1, Labels))
wqln <- subset(wqln,select=-c(RID, X, X.1, Labels))
wqca <- subset(wqca,select=-c(RID, X, X.1, Labels))
wqul <- subset(wqul,select=-c(RID, X, X.1, Labels))
wqhs <- subset(wqhs,select=-c(RID, X, X.1, Labels))
wqhspc <- subset(wqhspc,select=-c(RID, X, X.1, Labels))
wqmz <- subset(wqmz,select=-c(RID, X, X.1, Labels))
wqnsdv <- subset(wqnsdv,select=-c(RID, X, X.1, Labels))
wqbr <- subset(wqbr, select=-c(RID, X, X.1, Labels))

##Convert to matrix & flip
wqbkmat <- as.matrix(wqbk)
wqbkmat.r <-apply(wqbkmat,2,rev)
wqccmat <- as.matrix(wqcc)
wqccmat.r <-apply(wqccmat,2,rev)
wqlnmat <- as.matrix(wqln)
wqlnmat.r <-apply(wqlnmat,2,rev)
wqcamat <- as.matrix(wqca)
wqcamat.r <-apply(wqcamat,2,rev)
wqulmat <- as.matrix(wqul)
wqulmat.r <-apply(wqulmat,2,rev)
wqhsmat <- as.matrix(wqhs)
wqhsmat.r <-apply(wqhsmat,2,rev)
wqhspcmat <- as.matrix(wqhspc)
wqhspcmat.r <-apply(wqhspcmat,2,rev)
wqmzmat <- as.matrix(wqmz)
wqmzmat.r <-apply(wqmzmat,2,rev)
wqnsdvmat <- as.matrix(wqnsdv)
wqnsdvmat.r <-apply(wqnsdvmat,2,rev)
wqbrmat <- as.matrix(wqbr)
wqbrmat.r <-apply(wqbrmat,2,rev)

##Set colors and labels
col1 <- colorRampPalette(c("blue","green","yellow","orange","red"), space = "rgb")
col2 <- colorRampPalette(c("black","blue","green","yellow","orange","red"), space = "rgb")
labels <- c("Dec12","Jan13","Feb13","Mar13","Apr13","May13","Jun13","Jul13","Aug13","Sep13", "Oct13","Nov13","Dec13","Jan14","Feb14","Mar14","Apr14","May14","Jun14","Jul14","Aug14","Sep14", "Oct14", "Nov14", "Dec14")

##Display heatmap
tiff(file="X:/ArcProject/Arc_Heatmaps/Arc_Heatmaps/Arc_Final_CHL_BK.tiff")
hmwqbk <- heatmap.2(wqbkmat.r,Rowv=NULL,Colv=NULL,dendrogram=c("none"),trace="none",density.info="none", main="BK_Final_CHL", col=col1,labCol=labels,labRow=rev(wqbk2$Labels),cexRow=1.6, breaks=seq(0,100,by=0.025))
dev.off()
tiff(file="X:/ArcProject/Arc_Heatmaps/Arc_Heatmaps/Arc_Final_CHL_CC.tiff")
hmwqcc <- heatmap.2(wqccmat.r,Rowv=NULL,Colv=NULL,dendrogram=c("none"),trace="none",density.info="none", main="CC_Final_CHL", col=col1,labCol=labels,labRow=rev(wqcc2$Labels),cexRow=1.6, breaks=seq(0,50,by=0.025))
dev.off()
tiff(file="X:/ArcProject/Arc_Heatmaps/Arc_Heatmaps/Arc_Final_CHL_LN.tiff")
hmwqln <- heatmap.2(wqlnmat.r,Rowv=NULL,Colv=NULL,dendrogram=c("none"),trace="none",density.info="none", main="LN_Final_CHL", col=col1,labCol=labels,labRow=rev(wqln2$Labels),cexRow=1.6, breaks=seq(0,55,by=0.025))
dev.off()
tiff(file="X:/ArcProject/Arc_Heatmaps/Arc_Heatmaps/Arc_Final_CHL_CA.tiff")
hmwqca <- heatmap.2(wqcamat.r,Rowv=NULL,Colv=NULL,dendrogram=c("none"),trace="none",density.info="none", main="CA_Final_CHL", col=col1,labCol=labels,labRow=rev(wqca2$Labels),cexRow=1.6, breaks=seq(0,100,by=0.025))
dev.off()
tiff(file="X:/ArcProject/Arc_Heatmaps/Arc_Heatmaps/Arc_Final_CHL_UL.tiff")
hmwqul <- heatmap.2(wqulmat.r,Rowv=NULL,Colv=NULL,dendrogram=c("none"),trace="none",density.info="none", main="UL_Final_CHL", col=col1,labCol=labels,labRow=rev(wqul2$Labels),cexRow=1.6, breaks=seq(0,100,by=0.025))
dev.off()
tiff(file="X:/ArcProject/Arc_Heatmaps/Arc_Heatmaps/Arc_Final_CHL_HS.tiff")
hmwqhs <- heatmap.2(wqhsmat.r,Rowv=NULL,Colv=NULL,dendrogram=c("none"),trace="none",density.info="none", main="HS_Final_CHL", col=col1,labCol=labels,labRow=rev(wqhs2$Labels),cexRow=1.6, breaks=seq(0,80,by=0.025))
dev.off()
tiff(file="X:/ArcProject/Arc_Heatmaps/Arc_Heatmaps/Arc_Final_CHL_HSPC.tiff")
hmwqhspc <- heatmap.2(wqhspcmat.r,Rowv=NULL,Colv=NULL,dendrogram=c("none"),trace="none",density.info="none", main="HSPC_Final_CHL", col=col1,labCol=labels,labRow=rev(wqhspc2$Labels),cexRow=1.6, breaks=seq(0,30,by=0.025))
dev.off()
tiff(file="X:/ArcProject/Arc_Heatmaps/Arc_Heatmaps/Arc_Final_CHL_MZ.tiff")
hmwqmz <- heatmap.2(wqmzmat.r,Rowv=NULL,Colv=NULL,dendrogram=c("none"),trace="none",density.info="none", main="MZ_Final_CHL", col=col1,labCol=labels,labRow=rev(wqmz2$Labels),cexRow=1.6, breaks=seq(0,25,by=0.025))
dev.off()
tiff(file="X:/ArcProject/Arc_Heatmaps/Arc_Heatmaps/Arc_Final_CHL_NSDV.tiff")
hmwqnsdv <- heatmap.2(wqnsdvmat.r,Rowv=NULL,Colv=NULL,dendrogram=c("none"),trace="none",density.info="none", main="NSDV_Final_CHL", col=col1,labCol=labels,labRow=rev(wqnsdv2$Labels),cexRow=1.6, breaks=seq(0,75,by=0.025))
dev.off()
tiff(file="X:/ArcProject/Arc_Heatmaps/Arc_Heatmaps/Arc_Final_CHL_BR.tiff")
hmwqbr <- heatmap.2(wqbrmat.r,Rowv=NULL,Colv=NULL,dendrogram=c("none"),trace="none",density.info="none", main="BR_Final_CHL", col=col1,labCol=labels,labRow=rev(wqbr2$Labels),cexRow=1.6, breaks=seq(0,70,by=0.025))
dev.off()


#These show values over 20
tiff(file="X:/ArcProject/Arc_Heatmaps/Arc_Heatmaps/Arc_Final_CHL_BK_over20.tiff")
hmwqbk <- heatmap.2(wqbkmat.r,Rowv=NULL,Colv=NULL,dendrogram=c("none"),trace="none",density.info="none", main="BK_Final_CHL", col=col1,labCol=labels,labRow=rev(wqbk2$Labels),cexRow=1.6, breaks=seq(0,20,by=0.025))
dev.off()
tiff(file="X:/ArcProject/Arc_Heatmaps/Arc_Heatmaps/Arc_Final_CHL_CC_over20.tiff")
hmwqcc <- heatmap.2(wqccmat.r,Rowv=NULL,Colv=NULL,dendrogram=c("none"),trace="none",density.info="none", main="CC_Final_CHL", col=col1,labCol=labels,labRow=rev(wqcc2$Labels),cexRow=1.6, breaks=seq(0,20,by=0.025))
dev.off()
tiff(file="X:/ArcProject/Arc_Heatmaps/Arc_Heatmaps/Arc_Final_CHL_LN_over20.tiff")
hmwqln <- heatmap.2(wqlnmat.r,Rowv=NULL,Colv=NULL,dendrogram=c("none"),trace="none",density.info="none", main="LN_Final_CHL", col=col1,labCol=labels,labRow=rev(wqln2$Labels),cexRow=1.6, breaks=seq(0,20,by=0.025))
dev.off()
tiff(file="X:/ArcProject/Arc_Heatmaps/Arc_Heatmaps/Arc_Final_CHL_CA_over20.tiff")
hmwqca <- heatmap.2(wqcamat.r,Rowv=NULL,Colv=NULL,dendrogram=c("none"),trace="none",density.info="none", main="CA_Final_CHL", col=col1,labCol=labels,labRow=rev(wqca2$Labels),cexRow=1.6, breaks=seq(0,20,by=0.025))
dev.off()
tiff(file="X:/ArcProject/Arc_Heatmaps/Arc_Heatmaps/Arc_Final_CHL_UL_over20.tiff")
hmwqul <- heatmap.2(wqulmat.r,Rowv=NULL,Colv=NULL,dendrogram=c("none"),trace="none",density.info="none", main="UL_Final_CHL", col=col1,labCol=labels,labRow=rev(wqul2$Labels),cexRow=1.6, breaks=seq(0,20,by=0.025))
dev.off()
tiff(file="X:/ArcProject/Arc_Heatmaps/Arc_Heatmaps/Arc_Final_CHL_HS_over20.tiff")
hmwqhs <- heatmap.2(wqhsmat.r,Rowv=NULL,Colv=NULL,dendrogram=c("none"),trace="none",density.info="none", main="HS_Final_CHL", col=col1,labCol=labels,labRow=rev(wqhs2$Labels),cexRow=1.6, breaks=seq(0,20,by=0.025))
dev.off()
tiff(file="X:/ArcProject/Arc_Heatmaps/Arc_Heatmaps/Arc_Final_CHL_HSPC_over20.tiff")
hmwqhspc <- heatmap.2(wqhspcmat.r,Rowv=NULL,Colv=NULL,dendrogram=c("none"),trace="none",density.info="none", main="HSPC_Final_CHL", col=col1,labCol=labels,labRow=rev(wqhspc2$Labels),cexRow=1.6, breaks=seq(0,20,by=0.025))
dev.off()
tiff(file="X:/ArcProject/Arc_Heatmaps/Arc_Heatmaps/Arc_Final_CHL_MZ_over20.tiff")
hmwqmz <- heatmap.2(wqmzmat.r,Rowv=NULL,Colv=NULL,dendrogram=c("none"),trace="none",density.info="none", main="MZ_Final_CHL", col=col1,labCol=labels,labRow=rev(wqmz2$Labels),cexRow=1.6, breaks=seq(0,20,by=0.025))
dev.off()
tiff(file="X:/ArcProject/Arc_Heatmaps/Arc_Heatmaps/Arc_Final_CHL_NSDV_over20.tiff")
hmwqnsdv <- heatmap.2(wqnsdvmat.r,Rowv=NULL,Colv=NULL,dendrogram=c("none"),trace="none",density.info="none", main="NSDV_Final_CHL", col=col1,labCol=labels,labRow=rev(wqnsdv2$Labels),cexRow=1.6, breaks=seq(0,20,by=0.025))
dev.off()
tiff(file="X:/ArcProject/Arc_Heatmaps/Arc_Heatmaps/Arc_Final_CHL_BR_over20.tiff")
hmwqbr <- heatmap.2(wqbrmat.r,Rowv=NULL,Colv=NULL,dendrogram=c("none"),trace="none",density.info="none", main="BR_Final_CHL", col=col1,labCol=labels,labRow=rev(wqbr2$Labels),cexRow=1.6, breaks=seq(0,20,by=0.025))
dev.off()